name: Test Nuget Feed URL

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Nuget Packages
      run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p ${{ secrets.NUGET_FEED_PASSWORD }}

