---
name: Validate Changes

on:
  push:
    branches:
      - main
      - 'release/**'

  pull_request_target:
    types: [merged]
  pull_request:
    types: [opened, synchronize]
  
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print-base-ref:
    runs-on: ubuntu-latest

    steps:
          # Runs the Super-Linter action
      - name: Run Super-Linter
        if: ${{ github.base_ref || github.ref_name != github.event.repository.default_branch}}
        uses: super-linter/super-linter/slim@v5.6.1
        env:
          # only log identified linting issues
          LOG_LEVEL: NOTICE
          # Only lint new and modified files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref || github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disable cpplint as it conflicts with clang-format
          VALIDATE_CPP: false

      - name: print to console
        if: ${{ github.base_ref || github.ref_name != github.event.repository.default_branch}}
        run: echo "Not on main branch"
          
